### ISSUE TITLE
Testing Workflow | Restructure repositories

### ISSUE THREAD

**Issue by blankdots** [NBISweden/LocalEGA#268]
In order to streamline the development, testing and build workflow we are aiming to split the LocalEGA repository as follows:
* add unit tests in python as LocalEGA implementation, automating if possible with https://tox.readthedocs.io/en/latest/
* move `deployment/` folder along with integration tests to another repo e.g. `LocalEGA-deploy`
* in the `LocalEGA-deploy` replace fake Eureka server with the Spring Eureka version

What we are aiming to achieve is (assuming tests pass): 
```
                                       Trigger
LocalEGA +-------> UnitTests +-------> Integration Tests
change             Travis              LocalEGA-deploy

```
Travis resources: 
* https://docs.travis-ci.com/user/triggering-builds/
* https://docs.travis-ci.com/user/build-stages/

**Comment by blankdots** [comment]
working `.travis.yml` config:
```yml
language: python

python: 3.6

services: docker

stages:
    # unit tests will run on push and PR
  - name: unit_tests
    if: type IN (push, pull_request)
    # integration tests will run on push and PR
  - name: integration_tests
    if: type IN (pull_request)

jobs:
  include:
    - stage: unit_tests
      python: 3.6
      before_script:
        - pip install tox-travis
      script: tox
    - stage: integration_tests
      before_script:
        - git clone https://github.com/repo/LocalEGA-deploy.git
        - cd LocalEGA-deploy && mkdir -p LocalEGA && cp -r ../lega LocalEGA/
        - cd docker
        - make bootstrap
        - sudo chown -R travis private
        - docker network create cega
        - docker-compose up -d ${DOCKER_CONTAINERS}
        - docker-compose ps
      script:
        - sleep 10
        - cd ../tests
        - mvn test -B

notifications:
  email: false
```
